"""Add premium features

Revision ID: b4f92420ea8c
Revises: 9535d7a54e89
Create Date: 2026-09-07 00:31:51.090356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f92420ea8c'
down_revision: Union[str, Sequence[str], None] = '9535d7a54e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('custom_alias', sa.String(), nullable=True))
    op.add_column('urls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('urls', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('urls', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_index(op.f('ix_urls_custom_alias'), 'urls', ['custom_alias'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_custom_alias'), table_name='urls')
    op.drop_column('urls', 'hashed_password')
    op.drop_column('urls', 'is_active')
    op.drop_column('urls', 'expires_at')
    op.drop_column('urls', 'custom_alias')
    # ### end Alembic commands ###
